.gitlab-ci.yml
Dockerfile
README.md
docs/misc/changelog.rst
stable_baselines3/common/identity_env.py
tests/test_distributions.py

Add continuous integration using Gitlab-CI.
Addresses part of #1 .

Add Gitlab CI

---

docs/misc/changelog.rst
stable_baselines3/common/buffers.py
stable_baselines3/common/vec_env/vec_normalize.py
tests/test_run.py
tests/test_vec_check_nan.py
tests/test_vec_normalize.py

Related issue #17
Part of code review I should have included earlier: I went through the coverage report and fixed major missing tests I could spot (e.g. missing test for a whole parameter/function).
- Add some missing tests for `VecNormalize`, `VecCheckNaN` and `PPO`.
- Removed `VecNormalize` functions `load/save_running_average` in favor `load/save`.
- Removed `use_gae` parameter from `RolloutBuffer.compute_returns_and_advantage`, as this was not accessible through any algorithms, and same can be achieved by providing `gae_lam=1.0` (already documented).

Add some missing tests, update VecNormalize and RolloutBuffer

---

docs/misc/changelog.rst
stable_baselines3/common/vec_env/subproc_vec_env.py

Updated changelog.
Fixes the close method of SubprocVecEnv to also close its remote environments. (see SB 2 issue 898)

Fixed SubprocVecEnv close.

---

docs/misc/changelog.rst
stable_baselines3/common/base_class.py
stable_baselines3/common/off_policy_algorithm.py
stable_baselines3/common/save_util.py
tests/test_save_load.py

Automatically creates folders when saving models.
I created an `open_path(path, mode, verbosity, suffix) -> io.BufferedIOBase` function that takes a path in the form of `str, pathlib.Path, io.BufferedIOBase`. If the path is either of `str, pathlib.Path`, it ensures that the path:
- exists
- has the correct extension (.zip, .pkl)  if the path doesn't include its own extension/suffix.
and opens it. If opening for writing and the path does not exist, it is created. If there is a conflict with a folder, a warning is raised and the path is changed to `{path}_2`. In both cases, a warning is raised. If verbosity is set to 2, and the path exists, another warning is raised. If opening to read, it attempts to read the file at path, if it fails, it attempts to read the file `{path}.suffix`, where …

Automatically create paths for saved objects

---

docs/misc/changelog.rst
stable_baselines3/common/policies.py

1. Add module.bias none check before initialization at `common.policies.BasePolicy.init_weights()` .
1. Updated changelog.
Closes #124

Fix ortho init when `bias=False` with custom policy

---

docs/misc/changelog.rst
stable_baselines3/ppo/ppo.py

I think I've found a minor bug in your PPO algo realisation.
See, in the main class PPO(OnPolicyAlgorithm), def train() function, after all the loops and main code there is a logging part:
logger.record("train/entropy_loss", np.mean(entropy_losses))
logger.record("train/policy_gradient_loss", np.mean(pg_losses))
logger.record("train/value_loss", np.mean(value_losses))
logger.record("train/approx_kl", np.mean(approx_kl_divs))
logger.record("train/clip_fraction", np.mean(clip_fraction))
logger.record("train/loss", loss.item())
logger.record("train/explained_variance", explained_var)
take a closer look at logging variables. While np.mean is used over lists of accumulated values everywhere, for clip fraction you have np.mean(clip_fraction), NOT clip_fractions. So you always log the fraction …

Fix PPO logging of clip_fractions

---

docs/misc/changelog.rst
stable_baselines3/common/base_class.py
stable_baselines3/common/save_util.py
stable_baselines3/common/utils.py
tests/test_predict.py
tests/test_save_load.py

Added a 'device' keyword argument to BaseAlgorithm.load(), to enable users to set the model to their device of choice.
Edited test_save_load to also test the load method with all possible devices.
Added the changes to the changelog (I'm not completely confident about the choice of words though).
Added a 'device' keyword argument with default value 'auto', similarly to the hard-coded value that was used before my change to BaseAlgorithm.load(), and forwarded it to the C'tor call inside the load method (instead of the hard-coded string parameter).
I'm using this repo for my research and when I work with simpler models (tiny MLP for example) it is actually faster to use the CPU even though my machine has a powerful GPU since the overhead of the calls is higher than the benefits.
Thus, when I …

Allow to set a device when loading a model

---

docs/misc/changelog.rst
stable_baselines3/common/cmd_util.py

The variable `vec_env_cls` is a type and not an instance of either DummyVecEnv or SubprocVecEnv, so I set the type of that variable to a Type which is the type of either of these classes.

Fix type annotation in make_vec_env

---

docs/misc/changelog.rst
stable_baselines3/td3/td3.py

This fixes #163.
Add logging for both the actor and critic loss in TD3. 

Add actor/critic loss logging to td3

---

.gitlab-ci.yml
docs/conda_env.yml
docs/conf.py
docs/guide/custom_policy.rst
docs/misc/changelog.rst
docs/modules/td3.rst
setup.py
stable_baselines3/common/__init__.py
stable_baselines3/common/callbacks.py
stable_baselines3/common/distributions.py
stable_baselines3/common/evaluation.py
stable_baselines3/common/policies.py
stable_baselines3/common/torch_layers.py
stable_baselines3/common/type_aliases.py
stable_baselines3/dqn/policies.py
stable_baselines3/sac/policies.py
stable_baselines3/td3/policies.py

- Add custom feature extractor example
- Add full custom policy example for on-policy algorithms
- Re-enable autodoc type hint extension (looks much nicer with the latest version) and fix some issues due to that
You can see the difference with those links:
current doc: https://stable-baselines3.readthedocs.io/en/master/modules/td3.html#parameters
this PR: https://stable-baselines3.readthedocs.io/en/doc-custom-policy/modules/td3.html#parameters
Addresses part of #10 and #166 
closes #144 
closes #168

Update docs (custom policy, type hints)

---

docs/guide/custom_policy.rst
docs/misc/changelog.rst
stable_baselines3/common/torch_layers.py
stable_baselines3/common/utils.py
stable_baselines3/sac/policies.py
stable_baselines3/td3/policies.py
tests/test_custom_policy.py
tests/test_run.py
tests/test_save_load.py
tests/test_sde.py
tests/test_utils.py

Feature described in #113, the main difference with the on-policy equivalent is that we don't allow shared layers (only in the feature extractor) and therefore, `net_arch` can be a dict.
closes #113 

Add custom arch for off-policy actor/critic networks

---

docs/misc/changelog.rst
stable_baselines3/common/logger.py
tests/test_logger.py

I've introduced a general `filter_excluded_keys` function which takes `key_values` and `key_excluded` dictionaries as well as a logging `_format` specifier to remove excluded keys from the  `key_values` dictionary. This function is then used in `JSONOutputFormat` and `CSVOutputFormat` to remove excluded keys before any further processing is done. In `HumanOutputFormat` I've simply added an additional check for the `log` format type. 
In `test_logger.py` I've introduced regression tests, that check that all `*Format` objects produce no output when the key written is excluded. To do that I've introduced a new `read_log` fixture, which reads the contents from files, captured standard output and Tensorboard events and wraps it in a content interface. The wrapper makes the test check more …

Fix ignoring the exclude in the logger's record function for json, csv and log logging formats

---

docs/misc/changelog.rst
stable_baselines3/common/policies.py

`MlpExtractor` defaults to using "auto" device when none is provided (i.e. GPU if available), and this also happened when `device="cpu"` was given to the agent (result of #141). These parameters are then moved to desired device by training algorithm after creation.
This update makes "cpu" the fallback device if none is provided. We might want to formalize that by default everything is put on "cpu" in policies and let learning algorithms do all the moving to right devices.
I could not come up for a reliable this as there is no way to release the memory used from CUDA-initialization (only for clearing any tensors), so if any previous testing code uses any CUDA parts then this can not be tested.
Closes #193

Fix initializing CUDA even when `device="cpu"` is used.

---

docs/misc/changelog.rst
stable_baselines3/common/env_checker.py
tests/test_env_checker.py

Fix `check_env` not checking if the env has a Dict actionspace before calling `_check_nan`
fixes #191 

add check to ensure action space is non-dict non-tuple for env_checker nan check

---

docs/misc/changelog.rst
stable_baselines3/a2c/a2c.py
stable_baselines3/ppo/ppo.py

Fix for arguments order of `explained_variance()`. This bug was mentioned in https://github.com/DLR-RM/stable-baselines3/issues/225. 
I have check this function is only used in `ppo.py` and `a2c.py`. (It could be checked again in this [link](https://github.com/DLR-RM/stable-baselines3/search?q=explained_variance&type=Code))
1. Change the argument order of `explained_variance()` in `ppo.py`
2. Change the argument order of `explained_variance()` in `a2c.py`
3. Update `changelog.rst`
closes #225 

Fix arguments order of `explained_variance()`

---

docs/misc/changelog.rst
stable_baselines3/common/save_util.py

Fix for saving big replay buffer, use pickle protocol>=4

---

docs/misc/changelog.rst
docs/misc/projects.rst
stable_baselines3/common/atari_wrappers.py

Added SUMO-RL (https://github.com/LucasAlegre/sumo-rl) as example project in the docs

Add SUMO-RL as example project in the docs

---

docs/misc/changelog.rst
docs/misc/projects.rst

I'm updating the project page of the documentation with a new entry: rl_reach (toolbox for running RL experiments based on SB3).
This addition to the documentation was discussed with @araffin by email. 
When running `make pytest`, 25 tests are failing (see test summary info below). This is strange since I didn't modify the source code, only the documentation. Most of these tests failing seem to be due to connection error, so maybe it can be ignored.
```bash
FAILED tests/test_identity.py::test_discrete[env2-PPO] - AssertionError: Mean reward below threshold: 87.20 < 90.00
FAILED tests/test_utils.py::test_make_vec_env[None-SubprocVecEnv-1-CartPole-v1] - ConnectionResetError: [Errno 104] Connection reset by peer
FAILED tests/test_utils.py::test_make_vec_env[None-SubprocVecEnv-1-<lambda>] - …
```

Added new project using SB3 in the documentation: rl_reach

---

docs/guide/examples.rst
docs/misc/changelog.rst

Add a note clarifying the need of resetting environment after loading it in a new script.
I also thought about adding assertion-checks but ideas I had interfered with other use cases so I just update docs for now. Feel free to comment on this.
Related issue #339

Add note on loading and resetting environments

---

docs/misc/changelog.rst
docs/misc/projects.rst

Per #69
I will say that primary interesting part of SuperSuit for stable baselines (in my mind at least). isn't really that it's a project using stable baselines, it's that solves a common annoying problem for Gym environments in a very clean manner.

Include SuperSuit in projects

---

CODE_OF_CONDUCT.md
docs/guide/callbacks.rst
docs/guide/custom_env.rst
docs/misc/changelog.rst
docs/modules/dqn.rst

Add code of conduct + update doc

---

README.md
docs/guide/install.rst
docs/misc/changelog.rst

This makes the command work in Zsh.
Command fails if package is not in quotation marks:
```
➜  stable-baselines3 git:(fix_extra_install_command) ✗ pip install stable-baselines3[extra]  
zsh: no matches found: stable-baselines3[extra]
```

Make installation command compatible with ZSH

---

docs/misc/changelog.rst
docs/modules/ddpg.rst
stable_baselines3/ppo/ppo.py

Add the Schulman KL Divergence estimator and moved the KL check before the gradient update.
See the below image for examples comparing before (`old_approx_kl`) and after (`approx_kl`) in a little practical experiment.
For more robust comparison of values given, see the below graph:
I have also validated that the training does indeed stop when the KL Divergence is too large.
closes #417 

Update PPO KL Divergence Estimator

---

docs/misc/changelog.rst
docs/modules/a2c.rst

Recurrent policies are not supported yet as of (https://github.com/DLR-RM/stable-baselines3/issues/160#issuecomment-694756355), but the docs say that A2C supports them. Changing it to avoid misleading.
closes #471 

Remove recurrent policies from A2C docs

---

docs/misc/changelog.rst
stable_baselines3/common/callbacks.py
tests/test_callbacks.py

Make `EvalCallback` dump the evaluation logs it records.
`EvalCallback`  records logs that can be used with Tensorboad, but does not dump them. These logs end up being dumped at a later timestep (thus a wrong timestep) when some other actor dumps its logs (e.g. the training algorithm).
This PR fixes this bug by making `EvalCallback` dump its logs at the timesteps they were recorded.
Closes #457.

Fix Inconsistencies with EvalCallback tensorboard logs

---

docs/misc/changelog.rst
stable_baselines3/common/vec_env/vec_normalize.py
tests/test_vec_normalize.py

Currently `VecNormalize` raises an error when attempting to wrap an environment with an observation space that is not `gym.spaces.Box`. This PR applies this check only when `norm_obs` is `True`, and adds a test for `VecNormalize` in a discrete-observation environment.
Some use cases have `VecNormalize` used just for normalizing reward. This should be possible in all environments, regardless of the observation.

VecNormalize: allow non-continuous observations when norm_obs is False

---

docs/misc/changelog.rst
stable_baselines3/common/monitor.py

Added ``newline="\n"`` when opening CSV monitor files so that each line ends with ``\r\n`` instead of ``\r\r\n`` on Windows while Linux environments are not affected
Related to #692

Eliminate extra empty lines in CSV monitor files on Windows

---

docs/guide/migration.rst
docs/misc/changelog.rst
docs/modules/a2c.rst

`eps` needs to go into the `optimizer_kwargs`as can be seen here https://github.com/DLR-RM/stable-baselines3/blob/75b6f3b3b0f207456d9dcac2c6e86e8e2a22115f/stable_baselines3/common/policies.py#L553
Following the original documentation I got the following error
```
2021/12/29 15:57:22 | File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 125, in _setup_model
2021/12/29 15:57:22 | **self.policy_kwargs # pytype:disable=not-instantiable
2021/12/29 15:57:22 |  
2021/12/29 15:57:22 | TypeError("__init__() got an unexpected keyword argument 'eps'")
```
- [ x] Documentation (update in the documentation)

Doc fix: A2C - fix guidance on RMSpropTFLike

---

docs/misc/changelog.rst
stable_baselines3/common/vec_env/vec_monitor.py
tests/test_vec_monitor.py

closes https://github.com/DLR-RM/stable-baselines3/issues/728
```
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv, VecMonitor
from gym.envs.registration import register
from stable_baselines3.common.envs.bit_flipping_env import BitFlippingEnv
register(
id="BitFlippingEnv-v1",
entry_point=BitFlippingEnv,
)
env = DummyVecEnv([lambda: gym.make("BitFlippingEnv-v1")]*4)
env = VecMonitor(env, info_keywords=("is_success",), filename="extra_info_vec")
model = PPO("MultiInputPolicy", env, verbose=1)
model.learn(total_timesteps=5000)
```

Fixed logging info_keywords in the VecMonitor class.

---

.gitlab-ci.yml
stable_baselines3/common/distributions.py
stable_baselines3/common/envs/bit_flipping_env.py
tests/test_sde.py

Our CI is currently failing because of `black`, because https://github.com/psf/black/pull/2726 formats `x ** y` as `x**y` if `y` is "simple".
This PR just runs black to reformat those files, should not be any semantic changes.
CI broken. 
Not updating the changelog as nothing user visible, but can do so if desired.

Autoformat code with black (new version complains about new things)

---

docs/misc/changelog.rst

I missed that https://github.com/DLR-RM/stable-baselines3/pull/734 documented the deprecation of gym <=0.20 in release 1.30 not release 1.41a0 as it should be -- hotfix to fix that.

[HOTFIX] Put gym deprecation in correct part of changelog

---

docs/misc/changelog.rst
stable_baselines3/common/torch_layers.py

Closes #736 
Docstring in MlpExtractor, as stated in #736 says "Constructs an MLP that receives observations as an input [...]". This can be confusing since it can use also the features from another "extractor" such a CNN or directly the observation. This PR aim at clarifying this information in the docstring.

Update docstring on MlpExtractor.  Resolves #736

---

docs/guide/integrations.rst
docs/misc/changelog.rst
stable_baselines3/common/logger.py

This PR adds the feature to log with MLflow via similar configuration like the TensorBoard logger.
The PR partly addresses the discussion in #428, especially the request regarding planned support of MLflow as logging framework by @EloyAnguiano.
MLflow logging can be implemented like TensorBoard extended the logger module `stabel_baselines3.common.logger`. Thereby, the following changes are proposed and implemented:
[mlflow/MLflow](https://github.com/mlflow/mlflow) competes in the tracking tool and framework ecosystem with TensorBoard, Weights&Biases or comet-ml. Though, it is an independent and open-source tracking tool with an active community. MLflow has gained track during the last year and proven to be a suitable tracking tool for ML and RL applications. One key point of MLflow are …

Add doc to use mlflow logger

---

docs/misc/changelog.rst
stable_baselines3/common/base_class.py

Sorry for reposting this. I had some issues with finding the PR template.
In the creation of the BaseAlgorithm class, when the environment from a given name is created, a check is being made to ensure the environment does not present a nested Dict/Tuple space.
This is done first by the check_for_nested_spaces function.
After the function was being called, similar logic was introduced immediately afterwards, to check the environment did not have nested Dict observation space. This seems to be a redundant operation, so I removed it.
If I did not take some side effect into consideration, please let me know.
No major problem, just redundancy avoided.
It's the closest one I can see to the type of change I introduce.
I think the current change is small enough to not need the update on the …

Removed redundant double-check of nested Dict

---

docs/misc/changelog.rst
stable_baselines3/common/buffers.py
tests/test_save_load.py

Prohibit the simultaneous use of `optimize_memory_usage = True` and `handle_timeout_termination = True` due to a bug discussed in  #934.
This implements the hotfix as discussed in #934 that will throw an exception if both `optimize_memory_usage = True` and `handle_timeout_termination = True`. 
It also modifies `test_warn_buffer()` that tests whether the model emits a warning if `optimize_memory_usage = True`. The default value of `handle_timeout_termination` is `True` and so this test would encounter the exception implemented as part of this hotfix. To avoid this issue the test is modified to set `handle_timeout_termination = False`, as this does not interfere with the emitting of the warning.

Prohibit simultaneous use of optimize_memory_usage and handle_timeout_termination

---

docs/misc/changelog.rst
stable_baselines3/common/base_class.py
stable_baselines3/common/off_policy_algorithm.py
stable_baselines3/common/on_policy_algorithm.py
tests/test_logger.py
tests/test_run.py

We compute the time elapsed in RL algorithms in order to log both the total time, and the FPS (reciprocal of time elapsed).
This PR changes this time elapsed computation to be a delta of `time.time_ns()`, which is around 2.3x more precise than `time.time()` (see [PEP 564](https://peps.python.org/pep-0564/#annex-clocks-resolution-in-python)). Additionally, to avoid the possibility of division by zero when computing FPS, it takes the maximum of the time delta and the float machine epsilon. This replaces a more ad-hoc approach in `OffPolicyAlgorithm` (not present in `OnPolicyAlgorithm`, strangely) of adding a fixed `1e-8` to the time elapsed.
I found that on Windows (lower precision timer than Linux) the computed time elapsed on quick environments for smaller numbers of timesteps would …

Use higher resolution time_ns() and avoid division by zero

---

docs/guide/install.rst
docs/misc/changelog.rst

If you want to use sb3 with gym > 0.23 you need to install @carlosluis fork of sb3. 
The github repo link in the docs was wrong. 
Changed it to 
`pip install git+https://github.com/carlosluis/stable-baselines3@fix_tests`
Closes https://github.com/DLR-RM/stable-baselines3/issues/999

Fix url in docs

---

docs/misc/changelog.rst
stable_baselines3/common/base_class.py

According to #1006, in the _init_callback method, the verbose parameter is not used when creating EvalCallback. Therefore I opened a PR to fix this situation.
This closes #1006.

Fixed missing verbose parameter passing (#1006)

---

docs/misc/changelog.rst
stable_baselines3/common/off_policy_algorithm.py
stable_baselines3/ddpg/ddpg.py
stable_baselines3/dqn/dqn.py
stable_baselines3/sac/sac.py
stable_baselines3/td3/td3.py

Fixes the incorrect type annotation of the replay_buffer_class argument in ``common.OffPolicyAlgorithm`` initializer, which required an instance instead of a class object.
Fixes #1039. 

Fix replay_buffer_class type annotation

---

docs/misc/changelog.rst
stable_baselines3/common/base_class.py
tests/test_save_load.py

You can now resume training with a different number of environments.
```python
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
model = PPO("MlpPolicy", "CartPole-v1")
model.learn(total_timesteps=2048)
model.save("ppo_cartpole")
del model
model = PPO.load("ppo_cartpole", env=make_vec_env("CartPole-v1", n_envs=2))
model.learn(total_timesteps=2048)
```
Closes #1018

Fix loading a model with different number of environments

---

stable_baselines3/common/policies.py

Forgotten in my review of #1061

Transfer `ABC` inheritance from `BaseModel` to `BasePolicy`

---

docs/misc/changelog.rst
stable_baselines3/common/buffers.py
stable_baselines3/common/monitor.py
stable_baselines3/common/vec_env/stacked_observations.py
tests/test_monitor.py

Two commits fix that `closes #1068`. I added two new lines (189 & 191) changing the logic of `stable_baselines3.common.monitor.ResultsWriter` (the rest of the changes to `monitor.py` are to update the docstring/comments), and added an accompanying unittest (into `test_monitor.py`).
closes #1068 
Before, when a `ResultsWriter` class (i.e. whenever a `stable_baselines3.common.monitor.Monitor` wrapper) is created, a file-handle to the provided `filename` is opened on [line:191](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/monitor.py#L191). If the `filename` contains any directories  (ether relative or absolute), all its parent directories MUST exists, otherwise a `FileNotFoundError` is raised. To avoid this, I updated …

Automatically create missing directories of ``filename``s passed to ``ResultsWriter``

---

docs/misc/changelog.rst
stable_baselines3/common/logger.py
tests/test_logger.py

Fixes an error whereby keys are considered duplicate when they share the same key but have different prefixes (tags), since the tag is stripped off the key dictionary in HumanOutputFormat. 
We add the tag to the key in the keys dictionary, so we keep track of both the tag and the key without the tag to prevent this unwanted collision.
Closes #1078.

Fix duplicate key error in HumanOutputFormat

---

docs/misc/changelog.rst
setup.py

flake8 is not compatible with importlib-metadata v5, see https://github.com/DLR-RM/stable-baselines3/pull/1086#pullrequestreview-1127661223

Fix importlib dependency

---

docs/misc/changelog.rst
stable_baselines3/common/env_util.py

According with what discussed in #894:
- The function itself was already working with callables, but it wasn't considerent in the type hint of the function's signature.
- Extended the description of the wrapper_class parameter with a link to a Github issue containing more details on the matter.
(Note: not sure to call it "bug", but it's still a change in the code that solves an issue, not only in the doc)

Updated type hint and extended docstring in make_vec_env and make_atari_env

---

docs/misc/changelog.rst
setup.py
stable_baselines3/common/base_class.py
stable_baselines3/common/evaluation.py
stable_baselines3/common/policies.py
stable_baselines3/common/type_aliases.py
stable_baselines3/dqn/dqn.py
tests/test_utils.py

Currently `evaluate_policy` expects a `model: BaseAlgorithm` i.e. RL algorithm. But it runs fine on any `BasePolicy`, as it just calls `model.predict()` which has an identical type signature between `BaseAlgorithm` and `BasePolicy` -- indeed, `BaseAlgorithm` just forwards it to the policy contained inside it. This PR introduces a `PolicyPredictor` protocol for anything that matches that `predict` type signature, and updates `evaluate_policy`'s type annotation to use that.
I ended up putting `PolicyPredictor` in `type_aliases.py` but I can see an argument for putting it in `policies.py`.
`Protocol` is only available Python >=3.8 so I had to use `typing_extensions` but per discussion in https://github.com/DLR-RM/stable-baselines3/pull/1043#discussion_r961688423 we already have this …

Update evaluate_policy type annotation to support policies as well as RL algorithms

---

docs/misc/changelog.rst
setup.cfg
stable_baselines3/common/base_class.py
tests/test_utils.py

See https://github.com/PyCQA/flake8/issues/1760 and https://github.com/DLR-RM/rl-baselines3-zoo/pull/318
I also create a branch to improve error message: https://github.com/PyCQA/flake8/compare/main...araffin:flake8:fix/improve-error-message?expand=1
I fixed the additional warnings that were raised.

Fixes for flake8 6.0

---

docs/misc/changelog.rst
stable_baselines3/common/atari_wrappers.py

closes https://github.com/DLR-RM/stable-baselines3/issues/1060

Fix Atari wrapper bug: tried to step environment that needs reset 

---

docs/misc/changelog.rst
stable_baselines3/ppo/ppo.py

This PR closes #1229. A new variable `num_updates` is created before the training loop and is initially set to `self.n_epochs`. If the loop does not stop early, everything is effectively the same. However, if the loop is stopped early due to `kl_target` being set, `num_updates` is set to the number of epochs that have occurred plus the current epoch (i.e. `num_updates = epoch + 1`).
This should ensure that `train/n_updates` is always the correct value.

Ensure train/n_updates metric accounts for early stopping of training loop

---

docs/misc/changelog.rst
stable_baselines3/common/base_class.py

change timestamp to episode for logging

---

docs/guide/install.rst
docs/misc/changelog.rst

See https://github.com/DLR-RM/stable-baselines3/pull/780#issuecomment-1442498721

Update doc about Gymnasium support

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/custom_env.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/question.yml
setup.py
stable_baselines3/common/envs/bit_flipping_env.py
stable_baselines3/common/logger.py

Improve issue templates to provide more guidance

---

docs/misc/changelog.rst
stable_baselines3/common/envs/bit_flipping_env.py

1. Create a helper function `_make_observation_space` which handles creating the observation space and checking that `discrete_obs_space` and `image_obs_space` do not conflict
2. Rename `self.obs_space` to `self._obs_space` to clarify it is for managing the internal state only. Added a comment explaining this
3. Better explain what each of the observation spaces mean in the documentation
These changes make it clearer to users how the internal `obs_space` member is being used as well as what each of the observation space variants mean.
closes #1691
Given that the changes are minor, I do not think it warrants a dedicated unit test (correct me if I'm wrong). You can …

BitFlippingEnv argument check and docs clarification

---

docs/guide/export.rst
docs/guide/rl_tips.rst
docs/misc/changelog.rst

With newer version of PyTorch and ONNX, it is much simpler to export SB3 models =)
closes https://github.com/DLR-RM/stable-baselines3/issues/1349

Update SB3 ONNX export documentation

---

README.md
docs/misc/changelog.rst
setup.py

Example given in README.md doesn't work for current version of gymnasium.
Running example on fresh install is causing following error:
```
UserWarning: You tried to call render() but no `render_mode` was passed to the env constructor.
warnings.warn("You tried to call render() but no `render_mode` was passed to the env constructor.")
```
Current version of gymnasium requires render mode to be set at initialization https://gymnasium.farama.org/content/migration-guide/#environment-render
Not a major thing, but super annoying when first example from docs doesn't work out of the box.

Fix example in README.md

---

docs/misc/changelog.rst
stable_baselines3/common/distributions.py

Fixed sum_independent_dims docstring to reflect output shape when input is 1D (#1828)
Doc update only
closes #1828 

Fix `sum_independent_dims` docstring to reflect output shape

---

docs/misc/changelog.rst
stable_baselines3/common/base_class.py

- closes #1847.
- Updates documentation/docstring for the parameter ``log_interval`` in the base class. 
- The documentation describes the ``log_interval`` parameter of PPO's  ``learn`` method as the "number of episodes before logging". 
- However, this description is applicable only to off-policy algorithms. Because of how PPO works logging is actually performed after every ``log_interval``*``n_steps`` steps of rollout collection (not ``log_interval`` episodes as the documentation describes.) (See Issue #1847)
- This description comes from the docstring for the ``learn`` method inside ``base_class.py`` which I have updated to differentiate how ``log_interval`` is employed for on-policy v/s offpolicy. 
Note: we are using a …

Fix docstring for ``log_interval`` to differentiate between on-policy/off-policy logging frequency

---

docs/guide/examples.rst

The variable `env` is not defined. The gym env we want to change is `vec_env`
This fixes a typo in the documentation
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] Documentation (update in the documentation)
- [x ] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)

Fix typo in examples.rst

---

docs/conda_env.yml
docs/misc/changelog.rst
docs/modules/dqn.rst
docs/modules/sac.rst
setup.py

closes #2013 
Also updated sphinx upper bound after testing.

Add note about SAC ent coeff optimization

---

docs/guide/examples.rst
docs/misc/changelog.rst

Update PyBullet example

---

docs/misc/changelog.rst
docs/modules/a2c.rst
docs/modules/ppo.rst
stable_baselines3/a2c/a2c.py
stable_baselines3/ddpg/ddpg.py
stable_baselines3/dqn/dqn.py
stable_baselines3/ppo/ppo.py
stable_baselines3/sac/sac.py
stable_baselines3/td3/td3.py

closes #2035 
Simple changes adding links to policy doc in policy_kwargs parameter description for all algorithms (except HER)

Add policy documentation links to policy_kwargs parameter

---

docs/misc/changelog.rst
docs/misc/projects.rst

Add FootstepNet Envs to doc projects page
Add FootstepNet Envs to doc projects page

Add FootstepNet Envs to doc project page

---

pyproject.toml
tests/test_save_load.py
tests/test_vec_envs.py

Fix tests and warnings when running locally with a GPU

---

docs/guide/custom_env.rst
docs/guide/examples.rst
docs/guide/sbx.rst
docs/misc/changelog.rst
stable_baselines3/common/env_checker.py
tests/test_vec_normalize.py

Update the doc to address recurrent issues/long standing ones.
closes https://github.com/DLR-RM/stable-baselines3/issues/1768
closes https://github.com/DLR-RM/stable-baselines3/issues/1823
closes https://github.com/DLR-RM/stable-baselines3/issues/1745
closes https://github.com/DLR-RM/stable-baselines3/issues/2052
closes https://github.com/DLR-RM/stable-baselines3/pull/2054

Doc update: custom envs, IsaacLab, Brax and dm_control

---

docs/guide/vec_envs.rst
docs/misc/changelog.rst

I added a note to the documentation, notifying the user of the possibility to wrap sub-environments using `make_vec_env`. (See #2075 )
closes https://github.com/DLR-RM/stable-baselines3/issues/2075

Clarify the use of Gym wrappers with `make_vec_env`

---

docs/guide/custom_env.rst

SB3 allows to use images as observations for custom environments. However, the current documentation is not 100% clear on the type of observation used. I believe that, especially since images' types are `np.uint8`, the clarity of the documentation can be enhanced by adding a minimal example, specifying that although the effective type seems to be discrete, images are handled through ``spaces.Box`` by SB3.
Minimal change in the custom env documentation guide.
See above. Mainly enhancing clarity of the documentation to work with custom environment defining images as input observations.

Clarifying the documentation for custom env using images as observations

---

docs/guide/export.rst
docs/misc/changelog.rst

Add example in the documentation for `MultiInputPolicy` SB3 model export to ONNX.
closes https://github.com/DLR-RM/stable-baselines3/issues/1873

Add ONNX export example for `MultiInputPolicy`

---

.github/workflows/ci.yml
docs/guide/examples.rst
docs/guide/integrations.rst
docs/misc/changelog.rst
stable_baselines3/common/policies.py

Update LunarLander and LunarLanderCountinuous versions from v2 to v3.
The version 2 of `LunarLander` and `LunarLanderContinuous` environments are deprecated by gymnasium. Running the examples throws the `DeprecatedEnv` error and the examples could not run successfully. A slight change can fix this issue. We need to update the versions of these environments in the code from v2 to v3. I have already searched for all the usages of these environments in the documentation and updated all of them in this PR.
For reproducing the problem, just run the examples with the latest stable version of gymnasium and you'll see these errors:
```bash
raise error.DeprecatedEnv(
...<2 lines>...
)
gymnasium.error.DeprecatedEnv: Environment version v2 for `LunarLander` is deprecated. Please use `LunarLander-v3` …
```

Update LunarLander and LunarLanderContinuous Environments from v2 to v3 in the Documentation
