DLR-RM/stable-baselines3

- README.md
- docs/misc/changelog.rst
> Add CONTRIBUTION.md link in README

- .readthedocs.yml
- docs/conf.py
- docs/guide/developer.rst
- docs/misc/changelog.rst
- docs/requirements.txt
Minor doc update, I will merge it when the tests pass.
> Doc update

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- CONTRIBUTING.md
- Makefile
- docs/misc/changelog.rst
- setup.cfg
- setup.py
- stable_baselines3/common/cmd_util.py
- stable_baselines3/common/identity_env.py
- stable_baselines3/common/noise.py
- stable_baselines3/common/vec_env/vec_transpose.py
- tests/test_distributions.py
- tests/test_envs.py
- tests/test_save_load.py
- tests/test_utils.py
- tests/test_vec_check_nan.py
- tests/test_vec_normalize.py
- Add `flake8` to lint code (and associated `make lint` command)
- Try Github Action (good candidate for CI)
- Cleanup some code using the linter
> Add flake8 linter and Github CI

- docs/common/cmd_utils.rst
- docs/index.rst
- docs/misc/changelog.rst
- docs/modules/a2c.rst
- docs/modules/ppo.rst
The python file name for cmd_util imports are written wrong in the documentation.
> fix cmd_util.py imports

- docs/misc/changelog.rst
- stable_baselines3/common/noise.py
- tests/test_utils.py
Vectorized Action Noise allows for multiple instances of
ActionNoiseProcesses to run in parallel. This makes it easier to
run TD3/SAC/DDPG with VecEnv.
The motivation behind this addition is that for OU or other noise processes we need the state to exist until the end of the trajectory. We can't use a single process for multiple parallel episodes as they have different lengths. Thus, stacked/vectorized processes allow us to keep the processes for as long as the particular episode goes.
closes #33
> Implemented Vectorized Action Noise

- docs/misc/changelog.rst
- docs/modules/td3.rst
Define `env` before it is used so that ``TD3`` example code block can be run without error
> Fix TD3 Example Code Documentation

- docs/misc/changelog.rst
- docs/misc/projects.rst
Added the reacher project to the examples of projects using Stable-Baselines 3.
To expand the list of use cases of Stable-Baselines 3 and provide links to useful code examples.
> Udacity Reacher Project with Unity

- docs/misc/changelog.rst
- stable_baselines3/common/base_class.py
- stable_baselines3/common/policies.py
> Ignore errors from new pytype version

- docs/misc/changelog.rst
- stable_baselines3/a2c/a2c.py
- stable_baselines3/ppo/ppo.py
1. Fix the approximate entropy calculation in PPO and A2C by negating its value.
2. Updated changelog.
Closes #127 
> Fix approximate entropy calculation in PPO and A2C

- .gitlab-ci.yml
- stable_baselines3/common/buffers.py
- stable_baselines3/common/policies.py
- stable_baselines3/common/save_util.py
- stable_baselines3/dqn/policies.py
- tests/test_custom_policy.py
- tests/test_distributions.py
- tests/test_vec_envs.py
> Update black version + update docker image

- docs/guide/callbacks.rst
- docs/misc/changelog.rst
- stable_baselines3/common/callbacks.py
- stable_baselines3/common/off_policy_algorithm.py
- stable_baselines3/common/on_policy_algorithm.py
- tests/test_callbacks.py
Added ``StopTrainingOnMaxEpisodes`` callback class to keep track of episodes the current number of episodes ran so far and stop training once the maximum number of episodes ``max_episodes`` is reached.
Closes #140. Also, further details about motivation and implementation discussions at #140. 
> Add StopTrainingOnMaxEpisodes to callback collection

- stable_baselines3/common/callbacks.py
> Fix f-string in max episodes callback

- docs/misc/changelog.rst
- stable_baselines3/common/buffers.py
- stable_baselines3/common/on_policy_algorithm.py
- tests/test_identity.py
Fix off-by-one computation (the last value was wrong), move a check out of the for loop and rename `value` to `values` to better reflect what is expected.
Note: unfortunately, I don't think there is a good way to add a test for that...
closes #183 
(similar to a previous PR but without the laziness ;) )
> Fix off-by-one GAE computation

- .gitignore
- docs/misc/changelog.rst
- stable_baselines3/common/cmd_util.py
- tests/test_utils.py
> Allow env_kwargs in make_vec_env when env ID string supplied

- docs/misc/changelog.rst
- stable_baselines3/common/cmd_util.py
- stable_baselines3/common/distributions.py
- stable_baselines3/common/policies.py
- stable_baselines3/common/torch_layers.py
- stable_baselines3/dqn/policies.py
- stable_baselines3/sac/policies.py
- stable_baselines3/td3/policies.py
- tests/test_cnn.py
- tests/test_run.py
- tests/test_save_load.py
- tests/test_utils.py
Fixes the issue that the feature extractor was shared between network and target.
I also added a test to prevent any regression.
Note: for TD3, the effective polyak coefficient for the feature extractor will 2 * tau now
I hope it is not an issue?
closes #135
> Fix off policy features extractor

- docs/misc/changelog.rst
- stable_baselines3/a2c/a2c.py
- stable_baselines3/common/base_class.py
- stable_baselines3/common/callbacks.py
- stable_baselines3/common/env_util.py
- stable_baselines3/common/evaluation.py
- stable_baselines3/common/off_policy_algorithm.py
- stable_baselines3/common/on_policy_algorithm.py
- stable_baselines3/common/policies.py
- stable_baselines3/common/sb2_compat/rmsprop_tf_like.py
- stable_baselines3/common/type_aliases.py
- stable_baselines3/common/utils.py
- stable_baselines3/ddpg/ddpg.py
- stable_baselines3/dqn/dqn.py
- stable_baselines3/dqn/policies.py
- stable_baselines3/ppo/ppo.py
- stable_baselines3/sac/policies.py
- stable_baselines3/sac/sac.py
- stable_baselines3/td3/policies.py
- stable_baselines3/td3/td3.py
I meant to review TD3 but ended up adding the signature to all callable type annotations in the codebase.
Adding the signature to callables in the type annotations improves documentation and gives a much better idea what kind of function must be passed.
> Add callable signatures to type annotations.

- docs/misc/changelog.rst
- stable_baselines3/common/policies.py
- stable_baselines3/common/utils.py
- stable_baselines3/dqn/dqn.py
- stable_baselines3/dqn/policies.py
- stable_baselines3/sac/policies.py
- stable_baselines3/td3/policies.py
- tests/test_predict.py
> Fix DQN predict shape for single Gym env

- docs/misc/changelog.rst
- stable_baselines3/her/her_replay_buffer.py
- tests/test_her.py
Fix bug where a full `HerReplayBuffer` leads to an index error.
Exclude current episode in the `sample` function if we have a full buffer as it is invalid.
closes #234 
> Fix bug with full HerReplayBuffer

- docs/misc/changelog.rst
- stable_baselines3/common/base_class.py
- tests/test_utils.py
> Automatically wrap with a Monitor when possible

- docs/guide/examples.rst
- docs/misc/changelog.rst
- stable_baselines3/a2c/a2c.py
- stable_baselines3/dqn/dqn.py
> Add learning rate schedule example

- docs/misc/changelog.rst
- stable_baselines3/a2c/a2c.py
- stable_baselines3/common/base_class.py
- stable_baselines3/common/off_policy_algorithm.py
- stable_baselines3/common/on_policy_algorithm.py
- stable_baselines3/dqn/dqn.py
- stable_baselines3/ppo/ppo.py
- stable_baselines3/sac/sac.py
- stable_baselines3/td3/td3.py
- tests/test_spaces.py
Added checks for supported action spaces to improve clarity of error messages for the user.
closes #253 
> Add supported action spaces checks

- CONTRIBUTING.md
- README.md
- docs/misc/changelog.rst
> Update github name of Maximilian Ernestus

- docs/misc/changelog.rst
- docs/modules/dqn.rst
Replace `Pendulum-v0` with `CartPole-v0`, otherwise the sample code will not run normally.
Update the code in Example. Replace `Pendulum-v0` with `CartPole-v0`, otherwise the sample code will not run normally.
- [] Bug fix (non-breaking change which fixes an issue)
- [] My change requires a change to the documentation.
> Update the code in Example.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom_env.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- README.md
- docs/guide/custom_policy.rst
- docs/guide/install.rst
- docs/misc/changelog.rst
- Update custom policy documentation to recommend separate networks for actor/critic
- Update README (bibtex syntax highlighting)
- Add discord link
closes #310 
closes #298 
> Update custom policy documentation

- docs/guide/algos.rst
- docs/misc/changelog.rst
> Correct typo in the docs

- docs/guide/custom_policy.rst
- docs/guide/examples.rst
- docs/misc/changelog.rst
Small fix to the Docs.
Provide the env when loading the model, to avoid env=None.
closes #327
> Update docs, Provide the env when loading the model (#327)

- .gitlab-ci.yml
- docs/misc/changelog.rst
- stable_baselines3/common/policies.py
A new version of black was released, this causes a minor update to the formatting.
I will upgrade the docker images too.
> Reformat with new black version

- docs/misc/changelog.rst
- stable_baselines3/common/base_class.py
- stable_baselines3/common/on_policy_algorithm.py
Added `policy_base` to the `OnPolicyAlgorithm` class definition, including a description in the method description.
closes #412 
> Policy Base for On-policy Algorithms (#412)

- docs/guide/custom_policy.rst
- docs/guide/examples.rst
- docs/misc/changelog.rst
- docs/modules/dqn.rst
> Doc update (custom policy + fix HER example)

- docs/conda_env.yml
- docs/guide/callbacks.rst
- docs/guide/migration.rst
- docs/misc/changelog.rst
- stable_baselines3/common/callbacks.py
- stable_baselines3/common/preprocessing.py
- stable_baselines3/common/torch_layers.py
- stable_baselines3/ppo/ppo.py
- tests/test_cnn.py
Various doc updates and fixes.
closes #446
closes #440
closes #438 (related to #160 )
closes #349
Tmp fix for https://github.com/readthedocs/sphinx_rtd_theme/issues/1115
> Documentation update

- docs/misc/changelog.rst
- stable_baselines3/common/buffers.py
Changed observation buffers definition in DictReplayBuffer to use the same dytpe as specified by the observation_space.
Without this change all observation buffers were always using float64, this leads to higher memory consumption and unnecessary casts.
Closes #484 
Should I put anything in the changelog? Quite a minor change and on a feature new to this release, not sure what I could write
> Corrected DictReplayBuffer observation dtype #484

- docs/guide/examples.rst
- docs/guide/vec_envs.rst
- docs/misc/changelog.rst
> Documentation fixes

- docs/guide/examples.rst
- docs/misc/changelog.rst
- docs/modules/a2c.rst
- docs/modules/ddpg.rst
- docs/modules/dqn.rst
- docs/modules/her.rst
- docs/modules/ppo.rst
- docs/modules/sac.rst
- docs/modules/td3.rst
Added a warning regarding the nature of examples in the docs.
Each file inside docs/modules/*.rst now has the following message displayed: "Examples are here only to show how to quickly run something. Optimized hyperparameters and proper training are done in the RL Zoo repository found here".
Closes #526 
> Docs examples warning - issue #526

- docs/misc/changelog.rst
- stable_baselines3/common/policies.py
This should  make creating custom `predict_proba` or other derivatives easier (`predict_q_values`, ...)
closes #385 
> Refactor `BasePolicy` predict

- docs/misc/changelog.rst
- docs/misc/projects.rst
> Add GEM project to project section of doc

- docs/misc/changelog.rst
- docs/misc/projects.rst
Per the request in [this issue](https://github.com/lucas-emery/rocket-league-gym/issues/24) on our repo, we have submitted an addition to the supported projects page.
> Add RLGym to project page

- docs/misc/changelog.rst
- docs/modules/ppo.rst
Fixes #585 
- [ x] Documentation (update in the documentation)
> Doc fix environment mixup

- docs/misc/changelog.rst
- docs/misc/projects.rst
Many thanks for this fantastic library, keep up the good work!
> Add highway-env to the list of projects using SB3

- docs/misc/changelog.rst
- docs/misc/projects.rst
Update documentation to include tactile-gym project 
> add tactile-gym to the list of projects using SB3

- docs/misc/changelog.rst
- docs/misc/projects.rst
Add the L5Kit DriverGym project to the documentation page of Stable Baselines3
> Add DriverGym project to SB3 project documentation

- docs/misc/projects.rst
Edited Authors of DriverGym project
> Edited Authors of DriverGym project

- docs/guide/export.rst
- docs/misc/changelog.rst
A short addition to the documentation about exporting to TFLite/Coral
The current documentation on exporting the model to other engines gives the user limitless power to create whatever they need - unfortunately, I, personally, had a lot of difficulty closing all the loops for my own project. Having figured it out, I created a repo that includes my code: https://github.com/chunky/sb3_to_coral
This PR reflects the suggestion by @Miffyli here: https://github.com/DLR-RM/stable-baselines3/issues/673
> Add a section on exporting to TFLite/Coral with demonstration

- docs/guide/examples.rst
- docs/misc/changelog.rst
- stable_baselines3/common/base_class.py
addresses #683, #614
closes #683
closes #614
Slightly improved the docs for `BaseAlgorithm.load`
Technically, BaseAlgorithm.load is a classmethod, and the docs somewhere mention that loading in-place does not work. However, this behavior might be simply confusing. Especially compared to, for example, tensorflow/keras loading in-place by default. So now it's explicitly explained in the function's doc-string. 
- [] My change requires a change to the documentation.
- [] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [] I have updated the documentation accordingly.
------------------
p.s. tbh, requiring to run an hour of tests for 3 lines of docsting changes is a bit extreme
> more verbose documentation regarding `.load` vs `.set_parameters` 

- docs/misc/changelog.rst
- stable_baselines3/common/off_policy_algorithm.py
- stable_baselines3/common/on_policy_algorithm.py
> Consistent use of `device` as keyword argument

- README.md
- docs/guide/algos.rst
- docs/guide/integrations.rst
- docs/guide/sb3_contrib.rst
- docs/index.rst
- docs/misc/changelog.rst
> Update SB3 Contrib doc (ARS) and W&B integration

- docs/misc/changelog.rst
- docs/misc/projects.rst
Added my furuta pendulum project to the project list in the docs.
> Add furuta pendulum project to project list

- docs/guide/custom_env.rst
- fixed the broken url on creating custom gym environment. Also added appropriate advice by citing official OpenAi gym documents.
- SB3 text tweaked.
In response to issue #755 I'm proposing the following changes in existing documentation on creating custom environments. The proposed modifications are committed in documentation file named, `custom_env.rst`
Closes #755 
> Custom environment page modified. Following fixes are committed in response to issue#755.

- docs/guide/custom_env.rst
- docs/misc/changelog.rst
Changed code block indentation from 2 spaces to 4 spaces for consistency.
Consistency in documentation.
> update docs fix indentation

- docs/common/logger.rst
- docs/guide/quickstart.rst
- docs/guide/tensorboard.rst
- docs/misc/changelog.rst
> Add explanation of logger output

- docs/guide/tensorboard.rst
- docs/misc/changelog.rst
Update documentation for the part of _Directly Accessing The Summary Writer_, namely the way to get `output_formats` in class `SummaryWriterCallback`
`Fix #820`  opened by myself
closes #820 
> Update tensorboard.rst in SummaryWriterCallback

- docs/misc/changelog.rst
- stable_baselines3/common/off_policy_algorithm.py
Simple follow-up on #829, removing some dead code
closes #829
Technically none of below since it is just cleaning dead code
> Removing dead code for handling time limits (see #829)

- stable_baselines3/common/vec_env/base_vec_env.py
> Missing `f` prefix on f-strings fix

- docs/guide/rl_tips.rst
- docs/misc/changelog.rst
- docs/modules/ppo.rst
> Update doc: PPO blog post and remark on timeouts

- .gitlab-ci.yml
> Fix gitlab coverage report

- docs/guide/integrations.rst
- docs/misc/changelog.rst
- stable_baselines3/common/base_class.py
- stable_baselines3/common/env_checker.py
- tests/test_envs.py
> Update doc and add check for unbounded action space

- docs/misc/changelog.rst
- stable_baselines3/common/base_class.py
- stable_baselines3/common/callbacks.py
- stable_baselines3/common/env_checker.py
- stable_baselines3/common/noise.py
- stable_baselines3/common/off_policy_algorithm.py
- stable_baselines3/common/save_util.py
- stable_baselines3/her/her_replay_buffer.py
Fix exception cause in base_class.py. This means that when there are chained exceptions, the text between the two exceptions describes their relationship correctly.
This addresses https://github.com/DLR-RM/stable-baselines3/issues/941 but doesn't solve all the instances, just one for starters. After it's accepted I'll do the rest.
For more context, see https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with
> Fix exception cause in base_class.py

- README.md
- docs/misc/changelog.rst
> Add Quentin to the list of maintainers

- docs/guide/callbacks.rst
- docs/misc/changelog.rst
- stable_baselines3/common/callbacks.py
- tests/test_callbacks.py
Edited `CheckpointCallback` to:
- Save `replay_buffer` if the attribute is present and is not `None`
- Save `VecNormalize` statistics if available
Closes #1016 
> `CheckpointCallback` can now save replay buffer and `VecNormalize`

- docs/guide/rl_tips.rst
"an history" -> "a history"
Updated minor grammatical error.
closes #1038
> Updated minor grammar error

- docs/misc/changelog.rst
- stable_baselines3/common/env_checker.py
- tests/test_envs.py
See #944. Duplicate #947, but simpler implementation.
closes #944 
closes #947 
> Raise error when observation keys and observation space keys don't match

- docs/misc/changelog.rst
- stable_baselines3/common/policies.py
Fixes #1027 by removing the definition of the forward() method since this is already defined by torch.
> Remove forward() method from common.policies.BaseModel

- docs/guide/custom_policy.rst
- docs/misc/changelog.rst
Added link to issue #1066 to the custom policy documentation (in the "note" of the [custom features extractor](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#custom-feature-extractor) section).
That issue provides a demo of how to actually implement a features extractor which is not shared between the actor and the critic networks.
Previously, the explanation provided in the documentation was a bit vague, so, after posting a demo on the issue #1066 , @araffin asked me to put a link to that issue in the docs.
---
**Note:** after executing `make format`, many files (42) have been changed, but none of them was modified by me. For this reasons, these changes are not included in this PR. If required, I'll include them in a subsequent commit.
---
Note: You can run …
> Updated custom policy docs

- docs/guide/callbacks.rst
- docs/guide/checking_nan.rst
- docs/guide/custom_env.rst
- docs/guide/examples.rst
- docs/guide/quickstart.rst
- docs/guide/tensorboard.rst
- docs/misc/changelog.rst
- docs/modules/her.rst
In #780, some changes are out of the scope of the PR. In particular the use of ``"`` for string representation in the documentation.
> Standardized the use of ``"`` for string representation

- docs/guide/imitation.rst
Updates the `imitation` docs page to provide a prominent link to the full `imitation` docs, which are more detailed.
Right now `imitation` page in the SB3 docs outrank the actual `imitation` docs on Google. I was introducing someone to the imitation lib, and thought it was a bit confusing that the top search result was just a short explainer page in the SB3 docs instead of the full library-specific readthedocs page. This change might help avoid some confusion.
(I haven't created an issue for this, since I discussed it with @AdamGleave already, but I can create one if needed.)
> Link to full imitation docs

- setup.cfg
Add documentation link in `setup.cfg` so that it appears in pypi
> Documentation link in setup.cfg

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/custom_env.yml
> Add textarea for trackbacks in issue templates

- docs/misc/changelog.rst
- stable_baselines3/common/base_class.py
- stable_baselines3/common/off_policy_algorithm.py
> Fix type annotation of ``policy`` in ``BaseAlgorithm`` and ``OffPolicyAlgorithm``

- docs/guide/integrations.rst
- docs/misc/changelog.rst
Based on #1128 I updated the documentation.
- Created a new tutorial colab that takes into account the new features such as `package_to_hub`. It is hosted on huggingface\huggingface_sb3 repo.
- Adding `package_to_hub` and `push_to_hub` in the documentation.
The only problem I have from now with the HTML version is that the link is not truncated:
- This solves the issue #1128, the documentation was outdated.
> Update Hugging Face 🤗 Integration Documentation

- docs/guide/integrations.rst
Follow-up of #1134 #1133 that was merged too quickly...
> Fix integration documentation

- README.md
- docs/misc/changelog.rst
Fixed grammatical, punctuation, and semantic errors in documentation.
Error-free documentation makes it easier for users to understand the underlying principles and motivates the contributors to add or propose functionalities in the code.
> Fixed errors in the documentation

- README.md
- docs/guide/examples.rst
- docs/guide/quickstart.rst
- docs/misc/changelog.rst
- docs/modules/her.rst
- setup.py
- stable_baselines3/common/atari_wrappers.py
- stable_baselines3/common/base_class.py
- stable_baselines3/common/env_checker.py
- stable_baselines3/common/envs/bit_flipping_env.py
- stable_baselines3/common/noise.py
- stable_baselines3/common/off_policy_algorithm.py
- stable_baselines3/td3/td3.py
- tests/test_callbacks.py
- tests/test_envs.py
- tests/test_predict.py
- tests/test_save_load.py
- tests/test_utils.py
- tests/test_vec_monitor.py
- tests/test_vec_normalize.py
As #780 grows, this PR is intended to improve its readability by transferring some changes that do not belong in it, or that can be made right now.
closes #1015
> Drop `gym.GoalEnv` and other minor changes from #780

- docs/misc/changelog.rst
- setup.cfg
- stable_baselines3/common/type_aliases.py
> Fix `stable_baselines3/common/type_aliases.py` type hint 

- .github/workflows/ci.yml
- docs/misc/changelog.rst
> Upgrade CI/github-actions

- docs/misc/changelog.rst
- setup.cfg
- stable_baselines3/common/preprocessing.py
> Fix `stable_baselines3/common/preprocessing.py` type hints

- docs/misc/changelog.rst
- setup.cfg
- stable_baselines3/common/atari_wrappers.py
> Fix `stable_baselines3/common/atari_wrappers.py` type hints

- docs/misc/changelog.rst
- setup.py
- stable_baselines3/common/buffers.py
- stable_baselines3/common/policies.py
- stable_baselines3/common/utils.py
- stable_baselines3/sac/sac.py
7.5% speedup on this example.
```python
from stable_baselines3 import DQN
DQN("CnnPolicy", "Pong-v4", learning_starts=10_000, buffer_size=30_000).learn(100_000)
```
> Construct tensors directly on GPUs

- .github/workflows/ci.yml
- docs/misc/changelog.rst
- setup.cfg
- setup.py
Python 3.10 is stable. See https://devguide.python.org/versions/
> Add support for Python 3.10

- docs/misc/changelog.rst
- docs/misc/projects.rst
Add a new repo [rl-exploration-baselines](https://github.com/yuanmingqi/rl-exploration-baselines) to the project page.
> Add RLeXplore to the project page

- setup.py
- stable_baselines3/common/buffers.py
- stable_baselines3/common/envs/identity_env.py
closes https://github.com/DLR-RM/stable-baselines3/issues/1290
> Downgrade `sphinx-autodoc-typehints`

- docs/misc/changelog.rst
- stable_baselines3/a2c/a2c.py
A dot was missing between two senteces in the A2C's docstring (parameter `gae_lambda`).
Even though the docstring was going to new line, in the [documentation](https://stable-baselines3.readthedocs.io/en/master/modules/a2c.html) it wasn't and it looked weird.
> Fixed typo in A2C's docstring

- stable_baselines3/a2c/a2c.py
- stable_baselines3/common/buffers.py
- stable_baselines3/common/callbacks.py
- stable_baselines3/common/evaluation.py
- stable_baselines3/common/logger.py
- stable_baselines3/common/off_policy_algorithm.py
- stable_baselines3/common/on_policy_algorithm.py
- stable_baselines3/common/policies.py
- stable_baselines3/common/results_plotter.py
- stable_baselines3/common/save_util.py
- stable_baselines3/common/vec_env/stacked_observations.py
- stable_baselines3/common/vec_env/vec_frame_stack.py
- stable_baselines3/common/vec_env/vec_video_recorder.py
- stable_baselines3/ddpg/ddpg.py
- stable_baselines3/dqn/dqn.py
- stable_baselines3/her/her_replay_buffer.py
- stable_baselines3/ppo/ppo.py
- stable_baselines3/sac/sac.py
- stable_baselines3/td3/td3.py
- tests/test_run.py
- tests/test_save_load.py
- tests/test_vec_normalize.py
Minor black formatting changes with v23.1
> Upgrade black formatting

- docs/guide/examples.rst
- docs/misc/changelog.rst
Gif creation works with Atari Environments using the script provided below.
> Remove Note from examples - Code works

- docs/misc/changelog.rst
- docs/misc/projects.rst
Added UAV_Navigation_DRL_AirSim to the project page
> Added UAV_Navigation_DRL_AirSim to the project page

- README.md
- docs/guide/custom_env.rst
- docs/guide/examples.rst
- docs/guide/quickstart.rst
- docs/guide/rl_tips.rst
- docs/misc/changelog.rst
- docs/modules/a2c.rst
- docs/modules/ddpg.rst
- docs/modules/dqn.rst
- docs/modules/her.rst
- docs/modules/ppo.rst
- docs/modules/sac.rst
- docs/modules/td3.rst
- setup.py
The documentation for custom env was outdated.
> Update outdated custom env doc

- docs/misc/changelog.rst
- docs/misc/projects.rst
Hi @qgallouedec it was nice chatting to you at ICLR! Thanks for telling me about the projects page in the SB3 documentation. I have added a section about the pink noise project. Is this what you had in mind?
> Add pink-noise-rl to projects docs

- docs/guide/rl.rst
- docs/misc/changelog.rst
As asked, I added the Deep Reinforcement Learning course link to the Documentation (Reinforcement Learning Resources Section)
Don't hesitate to ask if I need to add it somewhere else.
Changed was asked by @araffin 
> Add Deep Reinforcement Learning Course Link

- docs/guide/examples.rst
- docs/misc/changelog.rst
Two typos fixed in the "Callbacks: Evaluate Agent Performance" section of the examples. 
The code runs now
Make the doc actually working
No need, it's way too small a change
No need, it is a documentation change
> Update the Callbacks: Evaluate Agent Performance section of the Examples

- docs/README.md
- docs/misc/changelog.rst
- docs/misc/projects.rst
Add [mobile-env](https://github.com/stefanbschneider/mobile-env) as new community project to the docs.
I recently added a new example notebook for using `stable-baselines3` v2.0.0 with mobile-env, which I want to share.
> Docs: Add mobile-env to community projects

- stable_baselines3/common/monitor.py
> Ignore pytype error

- docs/misc/changelog.rst
- stable_baselines3/common/on_policy_algorithm.py
I added a call to `callback.update_locals(locals())` before calling `callback.on_rollout_end()` in the `collect_rollouts()` function in `OnPolicyAlgorithm`, as suggested by #864.
closes #864
> Fixes `update_locals()` in  `collect_rollouts()` of `OnPolicyAlgorithm`

- .readthedocs.yml
- docs/conf.py
> Fix read the doc default theme

- README.md
- docs/guide/examples.rst
- docs/misc/changelog.rst
- stable_baselines3/common/base_class.py
- stable_baselines3/common/callbacks.py
- stable_baselines3/common/env_checker.py
- stable_baselines3/common/monitor.py
- stable_baselines3/common/policies.py
- stable_baselines3/common/results_plotter.py
- stable_baselines3/common/running_mean_std.py
- stable_baselines3/common/torch_layers.py
- stable_baselines3/common/type_aliases.py
- stable_baselines3/common/vec_env/patch_gym.py
- stable_baselines3/common/vec_env/vec_normalize.py
- stable_baselines3/her/her_replay_buffer.py
- stable_baselines3/sac/policies.py
- stable_baselines3/td3/policies.py
- tests/test_buffers.py
- tests/test_cnn.py
- tests/test_dict_env.py
- tests/test_her.py
- tests/test_logger.py
- tests/test_vec_normalize.py
This PR fixes various typos across the repo
For obvious reasons, we should have proper spelling
> Fix various typos

- docs/guide/rl.rst
- docs/misc/changelog.rst
Add Decisions and Dragons site to RL resources docs page,.
Added site to resources after request from [here](https://github.com/jmacglashan/decisions_and_dragons/issues/3)
Note: I have not setup the SB3 environment and cannot run all the test, but I don't *think* it should be necessary for this simple of a change. Let me know if you'd prefer I did though!
> Add Decisions and Dragons site to resources

- stable_baselines3/common/save_util.py
- stable_baselines3/common/vec_env/vec_normalize.py
- tests/test_vec_envs.py
> Fix mypy error

- docs/guide/examples.rst
- docs/misc/changelog.rst
closes https://github.com/DLR-RM/stable-baselines3/issues/2070
> fix docs atari example by import ale_py

- Dockerfile
- docs/misc/changelog.rst
- scripts/build_docker.sh
See https://github.com/DLR-RM/rl-baselines3-zoo/issues/486, also switched to pip install as conda support was dropped by PyTorch.
> Fix docker GPU build

- docs/guide/algos.rst
- docs/guide/quickstart.rst
- docs/guide/rl_tips.rst
- docs/misc/changelog.rst
- stable_baselines3/common/base_class.py
closes https://github.com/DLR-RM/stable-baselines3/issues/1150
> Update doc about training exceeding total timesteps

- README.md
- docs/guide/algos.rst
- docs/guide/callbacks.rst
- docs/guide/checking_nan.rst
- docs/guide/custom_env.rst
- docs/guide/custom_policy.rst
- docs/guide/examples.rst
- docs/guide/export.rst
- docs/guide/install.rst
- docs/guide/integrations.rst
- docs/guide/migration.rst
Fix typos and grammar mistakes
> Fix typos and grammar mistakes
